### ISSUE TITLE
Fail to revert to previous version

### ISSUE THREAD

**Issue by Trevelian** [nextcloud/files_versions_s3#2] opened 2019-11-22 09:39 UTC
Hello,

Nextcloud 17.0.1
PHP 7.1 on Centos7

I enable the application "Versioning" and the new application "S3 Versioning"
I can download previous version but when I try to revert to it on Nextcloud it fail.

![Screenshot from 2019-11-22 10-26-21](https://user-images.githubusercontent.com/4093808/69414464-1cfb6a80-0d13-11ea-896c-25ca6b6440a5.png)

The log message :

`[webdav] Fatal: Aws\S3\Exception\S3Exception: Error executing "CopyObject" on "https://MYS3.LOCAL/nextcloud/urn%3Aoid%3A1573911"; AWS HTTP error: Client error: `PUT https://MYS3.LOCAL/nextcloud/urn%3Aoid%3A1573911` resulted in a `400 Bad Request` response:
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>InvalidBucketName</Code><Message>The specified bucket is not valid.< (truncated...)
 InvalidBucketName (client): The specified bucket is not valid. - <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>InvalidBucketName</Code><Message>The specified bucket is not valid.</Message><Resource>/nextcloud/urn%3Aoid%3A1573911</Resource><RequestId>1574414174826692</RequestId></Error> at <<closure>>

 0. /var/www/cloud/3rdparty/aws/aws-sdk-php/src/WrappedHttpHandler.php line 100
    Aws\WrappedHttpHandler->parseError("*** sensitive parameter replaced ***", GuzzleHttp\Psr7\Request {}, Aws\Command {}, [])
 1. /var/www/cloud/3rdparty/guzzlehttp/promises/src/Promise.php line 203
    Aws\WrappedHttpHandler->Aws\{closure}("*** sensitive parameters replaced ***")
 2. /var/www/cloud/3rdparty/guzzlehttp/promises/src/Promise.php line 174
    GuzzleHttp\Promise\Promise::callHandler(2, "*** sensitive parameter replaced ***", [GuzzleHttp\Prom ... }])
 3. /var/www/cloud/3rdparty/guzzlehttp/promises/src/RejectedPromise.php line 40
    GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}("*** sensitive parameters replaced ***")
 4. /var/www/cloud/3rdparty/guzzlehttp/promises/src/TaskQueue.php line 47
    GuzzleHttp\Promise\RejectedPromise::GuzzleHttp\Promise\{closure}("*** sensitive parameters replaced ***")
 5. /var/www/cloud/3rdparty/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php line 98
    GuzzleHttp\Promise\TaskQueue->run()
 6. /var/www/cloud/3rdparty/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php line 125
    GuzzleHttp\Handler\CurlMultiHandler->tick()
 7. /var/www/cloud/3rdparty/guzzlehttp/promises/src/Promise.php line 246
    GuzzleHttp\Handler\CurlMultiHandler->execute(true)
 8. /var/www/cloud/3rdparty/guzzlehttp/promises/src/Promise.php line 223
    GuzzleHttp\Promise\Promise->invokeWaitFn()
 9. /var/www/cloud/3rdparty/guzzlehttp/promises/src/Promise.php line 267
    GuzzleHttp\Promise\Promise->waitIfPending()
10. /var/www/cloud/3rdparty/guzzlehttp/promises/src/Promise.php line 225
    GuzzleHttp\Promise\Promise->invokeWaitList()
11. /var/www/cloud/3rdparty/guzzlehttp/promises/src/Promise.php line 267
    GuzzleHttp\Promise\Promise->waitIfPending()
12. /var/www/cloud/3rdparty/guzzlehttp/promises/src/Promise.php line 225
    GuzzleHttp\Promise\Promise->invokeWaitList()
13. /var/www/cloud/3rdparty/guzzlehttp/promises/src/Promise.php line 62
    GuzzleHttp\Promise\Promise->waitIfPending()
14. /var/www/cloud/3rdparty/aws/aws-sdk-php/src/AwsClientTrait.php line 58
    GuzzleHttp\Promise\Promise->wait()
15. /var/www/cloud/3rdparty/aws/aws-sdk-php/src/AwsClientTrait.php line 77
    Aws\AwsClient->execute(Aws\Command {})
16. /var/www/cloud/apps/files_versions_s3/lib/Versions/S3VersionProvider.php line 85
    Aws\AwsClient->__call("copyObject", [{Bucket: "nextc ... }])
17. /var/www/cloud/apps/files_versions_s3/lib/Versions/AbstractS3VersionBackend.php line 67
    OCA\FilesVersionsS3\Versions\S3VersionProvider->rollback(OC\Files\ObjectStore\S3 {}, "urn:oid:1573911", "NDl1RAmFAKEzMEQ ... 3")
18. /var/www/cloud/apps/files_versions/lib/Versions/VersionManager.php line 93
    OCA\FilesVersionsS3\Versions\AbstractS3VersionBackend->rollback(OCA\Files_Versions\Versions\Version {})
19. /var/www/cloud/apps/files_versions/lib/Sabre/VersionFile.php line 87
    OCA\Files_Versions\Versions\VersionManager->rollback(OCA\Files_Versions\Versions\Version {})
20. /var/www/cloud/apps/files_versions/lib/Sabre/RestoreFolder.php line 76
    OCA\Files_Versions\Sabre\VersionFile->rollBack()
21. /var/www/cloud/3rdparty/sabre/dav/lib/DAV/Tree.php line 158
    OCA\Files_Versions\Sabre\RestoreFolder->moveInto("target", "versions/trevelian/v ... 3", OCA\Files_Versions\Sabre\VersionFile {})
22. /var/www/cloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php line 642
    Sabre\DAV\Tree->move("versions/trevelian/v ... 3", "versions/trevelian/restore/target")
23. <<closure>>
    Sabre\DAV\CorePlugin->httpMove(Sabre\HTTP\Reque ... "}, Sabre\HTTP\Response {})
24. /var/www/cloud/3rdparty/sabre/event/lib/EventEmitterTrait.php line 105
    undefinedundefinedcall_user_func_array([Sabre\DAV\CorePlugin {},"httpMove"], [Sabre\HTTP\Requ ... }])
25. /var/www/cloud/3rdparty/sabre/dav/lib/DAV/Server.php line 479
    Sabre\Event\EventEmitter->emit("method:MOVE", [Sabre\HTTP\Requ ... }])
26. /var/www/cloud/3rdparty/sabre/dav/lib/DAV/Server.php line 254
    Sabre\DAV\Server->invokeMethod(Sabre\HTTP\Reque ... "}, Sabre\HTTP\Response {})
27. /var/www/cloud/apps/dav/lib/Server.php line 317
    Sabre\DAV\Server->exec()
28. /var/www/cloud/apps/dav/appinfo/v2/remote.php line 35
    OCA\DAV\Server->exec()
29. /var/www/cloud/remote.php line 163
    undefinedundefinedrequire_once("/var/www/cloud/ ... p")

MOVE /remote.php/dav/versions/trevelian/versions/1573911/NDl1RAmFAKEzMEQwNy0xMUVBLThDMEMtRUU4RDAwQkU2QTE3
from 10.104.136.8 by trevelian at 2019-11-22T10:16:14+01:00`

**Comment by mr-neal** [comment] 2019-12-06 16:46
Any update on this?

**Comment by icewind1991** [comment] 2020-01-14 15:46
I can't reproduce this? what s3 server are you using?

**Comment by Trevelian** [comment] 2020-01-16 23:05
Its a StorageGRID by NetApp.

**Comment by icewind1991** [comment] 2020-02-06 15:33
Should be fixed with 0.1.2

**Closed by icewind1991** 2020-02-06 15:33 UTC

**Comment by Trevelian** [comment] 2020-02-06 18:43
I just try it and I confirm, its fixed ! 
Thanks !
